language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
    #  - "3.7"
before_install:
 - pip install pytest codecov pytest-cov ipython nbformat nbconvert
 - pip install coverage coveralls
script:
 - python setup.py install
 - py.test --cov=makecite
after_success:
 - coveralls
